import { useEffect, useMemo, useState } from "react";

const quickQueries = [["Болит колено", "травматолог · УЗИ · реабилитация"], ["Кашель не проходит", "Белугина · спирометрия · красные флаги"], ["Не могу похудеть", "Черткова · анализы · лечение веса"], ["Хочу капельницу", "Садык · персональная схема · безопасность"], ["Кружится голова", "невролог · вопросы · диагностика"], ["После операции", "команда из 4 специалистов · реабилитация"], ["Давление скачет", "кардиолог · СМАД · ЭХОКГ"], ["Онемели пальцы", "невролог · УЗИ нерва · маршрутизация"]];
const apiBase = import.meta.env.VITE_API_URL || "/api";
const apiKey = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
const api = (path) => fetch(`${apiBase}${path}`, { headers: apiKey ? { apikey: apiKey } : {} }).then((r) => { if (!r.ok) throw new Error("API error"); return r.json(); });

export default function App() {
  const [cards, setCards] = useState([]); const [modules, setModules] = useState([]); const [query, setQuery] = useState("");
  const [module, setModule] = useState(""); const [kind, setKind] = useState("Все"); const [mode, setMode] = useState("all");
  const [current, setCurrent] = useState(null); const [favorites, setFavorites] = useState(() => new Set(JSON.parse(localStorage.getItem("gci_favorites") || "[]"))); const [error, setError] = useState("");
  const load = async () => { try { setError(""); const data = query.trim() ? await api(`/search?q=${encodeURIComponent(query)}${module ? `&module=${encodeURIComponent(module)}` : ""}`) : await api(`/cards?limit=200${module ? `&module=${encodeURIComponent(module)}` : ""}`); setCards(data.results); } catch { setError("Не удалось получить данные. Проверьте, что backend запущен."); } };
  useEffect(() => { api("/modules").then(setModules).catch(() => setError("Не удалось получить список направлений.")); }, []);
  useEffect(() => { const timer = setTimeout(load, 180); return () => clearTimeout(timer); }, [query, module]);
  const kinds = useMemo(() => ["Все", ...new Set(cards.map((c) => c.kind).filter(Boolean))], [cards]);
  const visible = useMemo(() => cards.filter((c) => (kind === "Все" || c.kind === kind) && (mode !== "favorites" || favorites.has(c.id))), [cards, kind, mode, favorites]);
  const redCount = cards.filter((c) => c.urgency === "Красная" || c.kind === "Красный флаг" || c.kind === "Безопасность").length;
  const toggleFavorite = (id) => { const next = new Set(favorites); next.has(id) ? next.delete(id) : next.add(id); setFavorites(next); localStorage.setItem("gci_favorites", JSON.stringify([...next])); };
  const chooseModule = (name) => { setModule(name); setMode("all"); setQuery(""); setKind("Все"); };
  const title = mode === "favorites" ? "Избранное" : module || (query ? `Результаты: «${query}»` : "Все знания");
  return <div className="shell">
    <aside className="sidebar"><div className="brand"><div className="logo">G</div><div><b>Green Clinic</b><small>Intelligence</small></div></div><div className="side-title">Режимы</div>
      <Nav active={mode === "all" && !module} onClick={() => chooseModule("")} label="Все знания" value={cards.length} /><Nav active={mode === "complaints"} onClick={() => setMode("complaints")} label="Пациент говорит…" value="AI" /><Nav active={mode === "favorites"} onClick={() => setMode("favorites")} label="Избранное" value={favorites.size} />
      <div className="side-title">Направления</div>{modules.map((item) => <Nav key={item.module} active={module === item.module} onClick={() => chooseModule(item.module)} label={item.module} value={item.count} />)}</aside>
    <section className="content"><div className="topbar"><div className="searchbox"><span className="search-icon">⌕</span><input value={query} onChange={(e) => { setQuery(e.target.value); setMode(e.target.value ? "complaints" : "all"); }} placeholder="Напишите словами пациента: «болит колено», «кашель не проходит», «хочу капельницу»" /><button className="search-clear" onClick={() => { setQuery(""); setModule(""); setMode("all"); setKind("Все"); }}>Очистить</button></div></div>
      <main className="main"><section className="hero"><div><h1>Один запрос — готовый маршрут пациента</h1><p>Единый поиск по врачам, жалобам, услугам, исследованиям, готовым ответам, правилам общения и красным флагам.</p></div><div className="hero-badge"><b>{cards.length || "…"}</b><span>карточек объединено</span></div></section>
        <h3 className="quick-title">Попробуйте реальные запросы</h3><div className="quick-grid">{quickQueries.map(([q, description]) => <button key={q} className="quick" onClick={() => { setQuery(q); setMode("complaints"); }}><b>{q}</b><small>{description}</small></button>)}</div>
        <div className="stats"><Stat value={cards.length} label="карточек знаний" /><Stat value={modules.length} label="направлений" /><Stat value={redCount} label="карточек безопасности" /><Stat value="5–10 сек." label="до готового ответа" /></div>
        {query && visible.length > 0 && <Route cards={visible} query={query} />}<div className="toolbar"><h2>{title} · {visible.length}</h2><div className="chips">{kinds.map((item) => <button key={item} className={`chip ${kind === item ? "active" : ""}`} onClick={() => setKind(item)}>{item}</button>)}</div></div>
        <section className="results">{error ? <div className="empty">{error}</div> : visible.length ? visible.slice(0, 80).map((card) => <Card key={card.id} card={card} favorite={favorites.has(card.id)} onFavorite={() => toggleFavorite(card.id)} onOpen={() => setCurrent(card)} />) : <div className="empty">Ничего не найдено. Попробуйте описать жалобу другими словами или выберите направление слева.</div>}</section>
      </main></section>{current && <Drawer card={current} favorite={favorites.has(current.id)} onFavorite={() => toggleFavorite(current.id)} onClose={() => setCurrent(null)} />}</div>;
}
function Nav({ active, onClick, label, value }) { return <button className={`navbtn ${active ? "active" : ""}`} onClick={onClick}><span>{label}</span><span>{value}</span></button>; }
function Stat({ value, label }) { return <div className="stat"><b>{value}</b><span>{label}</span></div>; }
function Card({ card, favorite, onFavorite, onOpen }) { const red = card.urgency === "Красная"; return <article className="card" onClick={onOpen}><button className={`fav ${favorite ? "on" : ""}`} onClick={(e) => { e.stopPropagation(); onFavorite(); }}>{favorite ? "★" : "☆"}</button><div className="meta">{card.module} · {card.kind} · {card.id}</div><h3>{card.title}</h3><p>{card.quick}</p>{(red || card.urgency === "Оранжевая") && <div className={`flag ${red ? "red" : "orange"}`}>● {red ? "Красный флаг" : "Повышенное внимание"}</div>}<div className="tags">{(card.keywords || []).slice(0, 5).map((tag) => <span className="tag" key={tag}>{tag}</span>)}</div><div className="card-actions"><button className="smallbtn primary" onClick={(e) => { e.stopPropagation(); onOpen(); }}>Открыть</button><button className="smallbtn" onClick={(e) => { e.stopPropagation(); navigator.clipboard.writeText(card.quick); }}>Копировать</button></div></article>; }
function Route({ cards, query }) { const unique = (data, limit) => [...new Set(data.filter(Boolean))].slice(0, limit); const asks = unique(cards.flatMap((c) => c.ask || []), 6); const next = unique(cards.map((c) => c.next), 6); const flags = unique(cards.filter((c) => c.urgency === "Красная" || c.kind === "Красный флаг").map((c) => c.quick), 4); return <section className="route show"><h3>Интеллектуальная сводка по запросу: «{query}»</h3><div className="route-grid"><RouteCol title="Что уточнить" items={asks} fallback="Уточнить длительность, выраженность и наличие обследований." /><RouteCol title="Куда направить" items={next} fallback="Подобрать профильного специалиста по найденным карточкам." /><RouteCol title="Красные флаги" items={flags} fallback="Явных красных флагов в первых результатах не найдено." /></div><div className="notice">Сводка формируется из найденных карточек и не заменяет решение врача.</div></section>; }
function RouteCol({ title, items, fallback }) { return <div className="route-col"><b>{title}</b><ul>{(items.length ? items : [fallback]).map((item) => <li key={item}>{item}</li>)}</ul></div>; }
function Drawer({ card, favorite, onFavorite, onClose }) { const infos = [["Стоимость", card.price], ["Подготовка", card.prep], ["Длительность", card.duration], ["Специалист", card.doctor]].filter(([, value]) => value); return <div className="drawer open"><div className="shade" onClick={onClose} /><article className="sheet"><header className="sheet-head"><div className="meta">{card.module} · {card.kind} · {card.id}</div><h2>{card.title}</h2><button className="close" onClick={onClose}>✕</button></header><div className="sheet-body"><h4>Готовый ответ пациенту</h4><div className="answer">{card.patient_answer || card.quick}</div>{infos.map(([name, value]) => <div className="info" key={name}><b>{name}:</b> {value}</div>)}<Info title="Что уточнить" items={card.ask} fallback="Дополнительные вопросы не указаны." /><Info title="Что нельзя говорить" items={card.dont} fallback="Соблюдать общий стандарт общения Green Clinic." warning /><Info title="Следующий шаг" items={[card.next]} fallback="Подобрать запись по ситуации." /><Info title="Источник" items={[card.source]} fallback="Внутренняя база Green Clinic" /></div><div className="sheet-actions"><button className="action" onClick={onFavorite}>{favorite ? "★ В избранном" : "☆ В избранное"}</button><button className="action primary" onClick={() => navigator.clipboard.writeText(card.patient_answer || card.quick)}>Скопировать ответ</button></div></article></div>; }
function Info({ title, items = [], fallback, warning }) { return <div className={`block ${warning ? "warning" : ""}`}><h4>{title}</h4><ul>{(items.filter(Boolean).length ? items.filter(Boolean) : [fallback]).map((item) => <li key={item}>{item}</li>)}</ul></div>; }
